apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service-app
  template:
    metadata:
      labels:
        app: api-service-app
    spec:
      containers:
        - name: api-service-container
          image: siddharthtathagat77/loan_app:0.0.2
          ports:
            - containerPort: 8080
          env:
            - name: db.url
              value: "jdbc:mysql://policybazzar.cda40ce8goxx.eu-north-1.rds.amazonaws.com:3306/policyBazzar?createDatabaseIfNotExist=true"
            - name: db.username
              value: admin
            - name: db.password
              value: admin123
            - name: MYSQL_PORT
              value: "3306"

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api-service-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
  type: LoadBalancer
