apiVersion: v1
kind: Pod
metadata:
  name: mysqldb-pod
spec:
  containers:
    - name: mysqldb-container
      image: mysql:8.0.33
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_DATABASE
          value: policyBazzar
        - name: MYSQL_USER
          value: mysql
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_ROOT_PASSWORD
          value: password
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mysqldb-service
spec:
  selector:
    app: mysqldb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306